In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler


In [16]:
# y = a0 + a1*x1 + a2*x2 + ... + an*xn. 

In [17]:
class lin_reg:
    
    def __init__(self):
        self.a = None
        self.b = None
        
    def fit(self,X, y):
        X = np.asarray(X)
        y = np.asarray(y)
        
        z= np.zeros((X.shape[0],1))
        z[:,:]=1
        X_a0 = np.concatenate((z,X), axis=1)
        coef = np.linalg.inv(np.dot(X_a0.T,X_a0)).dot(X_a0.T).dot(y)
        self.a = coef[0]
        self.b = coef[1:]
        
    def predict(self,X):
        if (self.a == None and self.b == None):
            print('you mгst use the fit method first')
            return
        if X.shape[1] != self.b.shape[0]:
            print('Wrong shape X')
        return self.a + np.dot(X, self.b)
    

In [18]:
X = np.array([[1, 3, 2], [1, 2, 4], [2, 1, 5], [2, 3, 6]])
y = np.dot(X, np.array([1, 2, 3])) + 3

In [19]:
print(X)
print(y)

[[1 3 2]
 [1 2 4]
 [2 1 5]
 [2 3 6]]
[16 20 22 29]


In [20]:
model = lin_reg()
model.fit(X,y)

In [21]:
print(model.a)
print(model.b)

3.0000000000002807
[1. 2. 3.]


In [22]:
model.predict(X)

array([16., 20., 22., 29.])

## Проверка

In [23]:
modelLR = LinearRegression()
modelLR.fit(X, y)
modelLR.predict(X)

array([16., 20., 22., 29.])

In [24]:
print(modelLR.intercept_)
print(modelLR.coef_)

3.0000000000000036
[1. 2. 3.]


In [25]:
## Замечения - проблемы могут возникнуть при вычислении обратной матрицы, 
## для вычисления больших матриц, надо придумывать что-то получше.

## Используя  StandardScaler

In [26]:
scaler =  StandardScaler()
X_scaler = scaler.fit_transform(X)

/home/x350/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/x350/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [27]:
print(X_scaler)
print(y)

[[-1.          0.90453403 -1.52127766]
 [-1.         -0.30151134 -0.16903085]
 [ 1.         -1.50755672  0.50709255]
 [ 1.          0.90453403  1.18321596]]
[16 20 22 29]


In [28]:
model = lin_reg()
model.fit(X_scaler,y)
model.predict(X_scaler)

array([16., 20., 22., 29.])

In [29]:
model_lin = LinearRegression()
model_lin.fit(X_scaler, y)
model_lin.predict(X_scaler)

array([16., 20., 22., 29.])