In [1]:
import numpy as np

## квадратная матрица

In [2]:
# исходная матрица
A = np.array([[3,7], [5,2]])
A

array([[3, 7],
       [5, 2]])

In [3]:
# SVD разложение
u, s, vt = np.linalg.svd(A, full_matrices=False)
u.shape, s.shape, vt.shape

((2, 2), (2,), (2, 2))

In [4]:
# диагональная матрица 
D = np.diag(s)
# восстановление матрицы
print(np.dot(u, np.dot(D, vt)))

[[3. 7.]
 [5. 2.]]


### $$ n \neq m $$

In [5]:
n = 6
m = 7
X = np.random.randint(0, 5, size=(n, m))
X

array([[1, 4, 2, 3, 2, 2, 4],
       [3, 2, 2, 4, 2, 1, 4],
       [4, 2, 4, 3, 0, 4, 0],
       [3, 2, 3, 0, 4, 2, 3],
       [1, 3, 3, 3, 4, 3, 2],
       [0, 1, 0, 4, 2, 4, 3]])

In [6]:
u, s, vt = np.linalg.svd(X, full_matrices=True)
u.shape, s.shape, vt.shape

((6, 6), (6,), (7, 7))

In [7]:
# диагональная матрица 
sig = np.zeros(X.shape)
sig[:X.shape[0], :X.shape[0]] = np.diag(s)
# восстановление матрицы
sig
B = u.dot(sig.dot(vt))
print(np.around(B))

[[ 1.  4.  2.  3.  2.  2.  4.]
 [ 3.  2.  2.  4.  2.  1.  4.]
 [ 4.  2.  4.  3.  0.  4.  0.]
 [ 3.  2.  3. -0.  4.  2.  3.]
 [ 1.  3.  3.  3.  4.  3.  2.]
 [ 0.  1.  0.  4.  2.  4.  3.]]


## понижение ранга матрицы и сравнение с оригинальной матрицой

In [8]:
factor = 5
D = np.diag(s[:factor])
np.max(X- np.dot(u[:,:factor], np.dot(D, vt[:factor:])))

0.5212286788661471

In [9]:
factor = 3
D = np.diag(s[:factor])
np.max(X- np.dot(u[:,:factor], np.dot(D, vt[:factor:])))

1.3834314561570125

## редуцирование

In [10]:
X.shape

(6, 7)

In [11]:
elements = 4
sig = sig[:, :elements]
vt = vt[:elements, :]

T = u.dot(sig)
T.shape

(6, 4)